include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "lib/l10n/*.i18n.dart"
    -
linter:
  rules:
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
