import '../../l10n/messages.i18n.dart';
import '../config/password_generator_config.dart';
import '../feedback/icontextual_password_feedback_provider.dart';
import '../feedback/ipassword_feedback_provider.dart';
import '../feedback/password_feedback_builder.dart';
import '../model/character_set_profile.dart';
import '../model/password_feedback.dart';
import '../model/password_feedback_context.dart';
import '../model/password_generation_exception.dart';
import '../model/password_strength.dart';
import '../normalizer/ipassword_normalizer.dart';
import '../normalizer/password_normalizer.dart';
import '../strategy/ipassword_generation_strategy.dart';
import '../strategy/policy_aware_password_strategy.dart';
import '../strategy/random_password_strategy.dart';
import '../strength_estimator/ipassword_strength_estimator.dart';
import '../strength_estimator/password_strength_estimator.dart';
import '../validator/config_aware_password_validator.dart';
import '../validator/iconfig_aware_password_validator.dart';
import '../validator/ipassword_validator.dart';
import 'ipassword_generator.dart';

/// Default [IPasswordGenerator] implementation using a strategy-based approach.
///
/// Generates passwords using `Random.secure()` (platform CSPRNG).
/// Not designed for cross-isolate use; create one instance per isolate.
final class PasswordGenerator implements IPasswordGenerator {
  /// Creates a [PasswordGenerator] with optional custom strategies.
  PasswordGenerator({
    IPasswordValidator? validator,
    IPasswordStrengthEstimator? strengthEstimator,
    IPasswordGenerationStrategy? generationStrategy,
    IPasswordFeedbackProvider? feedbackProvider,
    IPasswordNormalizer? normalizer,
  }) : _validator = validator ?? ConfigAwarePasswordValidator(),
       _strengthEstimator = strengthEstimator ?? PasswordStrengthEstimator(),
       _generationStrategy = generationStrategy ?? RandomPasswordStrategy(),
       _feedbackProvider = feedbackProvider ?? PasswordFeedbackBuilder(),
       _normalizer = normalizer ?? DefaultPasswordNormalizer() {
    _policyAwareStrategy = PolicyAwarePasswordStrategy(
      baseStrategy: _generationStrategy,
    );
  }

  final IPasswordValidator _validator;
  final IPasswordStrengthEstimator _strengthEstimator;
  final IPasswordGenerationStrategy _generationStrategy;
  late final IPasswordGenerationStrategy _policyAwareStrategy;
  final IPasswordFeedbackProvider _feedbackProvider;
  final IPasswordNormalizer _normalizer;
  PasswordGeneratorConfig? _config;
  String? _lastGeneratedPassword;

  /// The last password generated by this instance, or `null` if none.
  String? get lastPassword => _lastGeneratedPassword;

  /// Updates the configuration used for subsequent generations.
  void updateConfig(PasswordGeneratorConfig config) {
    assert(
      config.maxGenerationAttempts > 0,
      'maxGenerationAttempts must be greater than 0',
    );
    _config = config;
  }

  @override
  String refreshPassword() {
    final config = _resolveConfig();
    final maxAttempts = config.maxGenerationAttempts;
    if (maxAttempts <= 0) {
      final messages = const Messages();
      throw ArgumentError(messages.error.maxGenerationAttemptsPositive);
    }

    for (var attempt = 0; attempt < maxAttempts; attempt++) {
      final normalized = _generatePassword(config, trackLast: false);
      if (_validator is IConfigAwarePasswordValidator) {
        if ((_validator).isStrongPasswordWithConfig(normalized, config)) {
          _lastGeneratedPassword = normalized;
          return normalized;
        }
      } else if (_validator.isStrongPassword(normalized)) {
        _lastGeneratedPassword = normalized;
        return normalized;
      }
    }

    throw PasswordGenerationException.maxAttemptsExceeded(
      maxAttempts: maxAttempts,
    );
  }

  @override
  String generatePassword({
    int? length,
    bool? useUpperCase,
    bool? useLowerCase,
    bool? useNumbers,
    bool? useSpecialChars,
    bool? excludeAmbiguousChars,
  }) {
    final settings = _resolveConfig(
      length: length,
      useUpperCase: useUpperCase,
      useLowerCase: useLowerCase,
      useNumbers: useNumbers,
      useSpecialChars: useSpecialChars,
      excludeAmbiguousChars: excludeAmbiguousChars,
    );

    return _generatePassword(settings);
  }

  /// Estimates the [PasswordStrength] of the given [password].
  PasswordStrength estimateStrength(String password) {
    return _strengthEstimator.estimatePasswordStrength(
      _normalizer.normalize(password),
    );
  }

  @override
  PasswordFeedback estimateFeedback(String password) {
    final normalized = _normalizer.normalize(password);
    final config = _resolveConfig();
    final (baseEntropy, _) = _strengthEstimator.estimateDetailedStrength(
      normalized,
    );
    final entropy =
        config.policy?.allowSpaces == true
            ? _strengthEstimator.estimateEntropy(normalized, allowSpaces: true)
            : baseEntropy;
    final strength = _strengthEstimator.estimatePasswordStrength(normalized);

    if (_feedbackProvider is IContextualPasswordFeedbackProvider) {
      final context = PasswordFeedbackContext(
        password: password,
        normalizedPassword: normalized,
        strength: strength,
        entropy: entropy,
        config: config,
      );
      return (_feedbackProvider).buildWithContext(context);
    }

    return _feedbackProvider.build(strength);
  }

  PasswordGeneratorConfig _resolveConfig({
    int? length,
    bool? useUpperCase,
    bool? useLowerCase,
    bool? useNumbers,
    bool? useSpecialChars,
    bool? excludeAmbiguousChars,
  }) {
    return PasswordGeneratorConfig(
      length: length ?? _config?.length ?? 16,
      useUpperCase: useUpperCase ?? _config?.useUpperCase ?? true,
      useLowerCase: useLowerCase ?? _config?.useLowerCase ?? true,
      useNumbers: useNumbers ?? _config?.useNumbers ?? true,
      useSpecialChars: useSpecialChars ?? _config?.useSpecialChars ?? true,
      excludeAmbiguousChars:
          excludeAmbiguousChars ?? _config?.excludeAmbiguousChars ?? false,
      characterSetProfile:
          _config?.characterSetProfile ?? CharacterSetProfile.defaultProfile,
      maxGenerationAttempts:
          _config?.maxGenerationAttempts ??
          PasswordGeneratorConfig.defaultMaxGenerationAttempts,
      policy: _config?.policy,
      extra: _config?.extra ?? const {},
    );
  }

  String _generatePassword(
    PasswordGeneratorConfig config, {
    bool trackLast = true,
  }) {
    final password = _policyAwareStrategy.generate(config);
    final normalized = _normalizer.normalize(password);
    if (trackLast) {
      _lastGeneratedPassword = normalized;
    }
    return normalized;
  }
}
