import '../config/password_generator_config.dart';
import '../model/character_set_profile.dart';
import '../model/password_generation_exception.dart';
import '../model/password_strength.dart';
import '../strategy/ipassword_generation_strategy.dart';
import '../strategy/random_password_strategy.dart';
import '../strength_estimator/ipassword_strength_estimator.dart';
import '../strength_estimator/password_strength_estimator.dart';
import '../validator/ipassword_validator.dart';
import '../validator/password_validator.dart';
import 'ipassword_generator.dart';

/// A concrete implementation of [IPasswordGenerator] for generating secure passwords.
///
/// This class uses a modular, strategy-based approach to generate passwords.
/// It can be configured with different validation, strength estimation, and
/// generation strategies to provide a flexible and extensible password
/// generation solution.
class PasswordGenerator implements IPasswordGenerator {
  /// Creates a [PasswordGenerator] with optional custom strategies.
  ///
  /// The [validator], [strengthEstimator], and [generationStrategy] parameters
  /// allow for the injection of custom implementations. If any of these are
  /// not provided, default implementations will be used.
  PasswordGenerator({
    IPasswordValidator? validator,
    IPasswordStrengthEstimator? strengthEstimator,
    IPasswordGenerationStrategy? generationStrategy,
  }) : _validator = validator ?? PasswordValidator(),
       _strengthEstimator = strengthEstimator ?? PasswordStrengthEstimator(),
       _generationStrategy = generationStrategy ?? RandomPasswordStrategy();

  final IPasswordValidator _validator;
  final IPasswordStrengthEstimator _strengthEstimator;
  final IPasswordGenerationStrategy _generationStrategy;
  PasswordGeneratorConfig? _config;
  String? _lastGeneratedPassword;

  /// Returns the last password generated by this instance.
  ///
  /// If no password has been generated yet, this will be `null`.
  String? get lastPassword => _lastGeneratedPassword;

  /// Updates the password generation configuration.
  ///
  /// The provided [config] will be used for subsequent password generations.
  void updateConfig(PasswordGeneratorConfig config) {
    _config = config;
  }

  @override
  String refreshPassword() {
    final maxAttempts =
        _config?.maxGenerationAttempts ??
        PasswordGeneratorConfig.defaultMaxGenerationAttempts;
    if (maxAttempts <= 0) {
      throw ArgumentError('maxGenerationAttempts must be greater than 0');
    }

    for (var attempt = 0; attempt < maxAttempts; attempt++) {
      final password = generatePassword();
      if (_validator.isStrongPassword(password)) {
        return password;
      }
    }

    throw PasswordGenerationException.maxAttemptsExceeded(
      maxAttempts: maxAttempts,
    );
  }

  @override
  String generatePassword({
    int? length,
    bool? useUpperCase,
    bool? useLowerCase,
    bool? useNumbers,
    bool? useSpecialChars,
    bool? excludeAmbiguousChars,
  }) {
    final settings = PasswordGeneratorConfig(
      length: length ?? _config?.length ?? 12,
      useUpperCase: useUpperCase ?? _config?.useUpperCase ?? true,
      useLowerCase: useLowerCase ?? _config?.useLowerCase ?? true,
      useNumbers: useNumbers ?? _config?.useNumbers ?? true,
      useSpecialChars: useSpecialChars ?? _config?.useSpecialChars ?? true,
      excludeAmbiguousChars:
          excludeAmbiguousChars ?? _config?.excludeAmbiguousChars ?? false,
      characterSetProfile:
          _config?.characterSetProfile ?? CharacterSetProfile.defaultProfile,
      maxGenerationAttempts:
          _config?.maxGenerationAttempts ??
          PasswordGeneratorConfig.defaultMaxGenerationAttempts,
      extra: _config?.extra ?? const {},
    );

    final password = _generationStrategy.generate(settings);
    _lastGeneratedPassword = password;
    return password;
  }

  /// Estimates the strength of a given [password].
  ///
  /// Returns a [PasswordStrength] enum value indicating the estimated strength.
  PasswordStrength estimateStrength(String password) {
    return _strengthEstimator.estimatePasswordStrength(password);
  }
}
