name: Library CI

on:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - ".github/workflows/ci_lib.yaml"
      - ".github/workflows/reusable_verify.yaml"
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - ".github/workflows/ci_lib.yaml"
      - ".github/workflows/reusable_verify.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify.yaml
    with:
      working-directory: .
      sdk: flutter
    secrets: inherit
