name: Build and Deploy to Netlify

on:
  push:
    branches: [main]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify.yaml
    with:
      working-directory: example
      run-tests: true
    secrets: inherit

  deploy:
    needs: verify
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter Environment
        uses: ./.github/actions/setup-flutter
        with:
          flutter-version: ${{ secrets.FLUTTER_VERSION }}
          working-directory: example

      - name: Build web app
        run: flutter build web
        working-directory: example

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./example/build/web"
          production-branch: master
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
