name: Reusable Verification

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The directory where the command should be run"
        required: false
        default: "."
        type: string

      run-tests:
        description: "Whether to run tests"
        required: false
        default: true
        type: boolean
      analyze:
        description: "Whether to run analysis"
        required: false
        default: true
        type: boolean
      format:
        description: "Whether to check formatting"
        required: false
        default: true
        type: boolean

jobs:
  format:
    if: ${{ inputs.format }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter Environment
        uses: ./.github/actions/setup-flutter
        with:
          flutter-version: ${{ secrets.FLUTTER_VERSION }}
          working-directory: ${{ inputs.working-directory }}

      - name: Check formatting
        run: dart format --set-exit-if-changed .
        working-directory: ${{ inputs.working-directory }}

  analyze:
    if: ${{ inputs.analyze }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter Environment
        uses: ./.github/actions/setup-flutter
        with:
          flutter-version: ${{ secrets.FLUTTER_VERSION }}
          working-directory: ${{ inputs.working-directory }}

      - name: Analyze code
        run: flutter analyze --fatal-infos .
        working-directory: ${{ inputs.working-directory }}

  test:
    if: ${{ inputs.run-tests }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter Environment
        uses: ./.github/actions/setup-flutter
        with:
          flutter-version: ${{ secrets.FLUTTER_VERSION }}
          working-directory: ${{ inputs.working-directory }}

      - name: Run tests
        run: flutter test
        working-directory: ${{ inputs.working-directory }}
